name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Compilaci贸n y ejecuci贸n
      id: compilacion-y-ejecucion
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Compilaci贸n y ejecuci贸n
        setup-command: g++ -o Ejercicio Ejercicio.cpp
        command: printf "3" | ./Ejercicio
        timeout: 10
        max-score: 5
    - name: Prueba de salida
      id: prueba-de-salida
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Prueba de salida
        setup-command: g++ -o Ejercicio Ejercicio.cpp
        command: "./Ejercicio"
        input: |-
          3\n
          2\n
          3
        expected-output: |-
          *
          **
          ***
          *
          **
          *
          **
          ***
        comparison-method: exact
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        COMPILACION-Y-EJECUCION_RESULTS: "${{steps.compilacion-y-ejecucion.outputs.result}}"
        PRUEBA-DE-SALIDA_RESULTS: "${{steps.prueba-de-salida.outputs.result}}"
      with:
        runners: compilacion-y-ejecucion,prueba-de-salida
